export const DECKS = ["Topology", "Real Analysis", "Abstract Algebra", "Linear Algebra", "Number Theory", "Probability", "Logic & Foundations"];

export const HARD_COUNTER = {
  Topology: "Real Analysis",
  "Real Analysis": "Topology",
  "Abstract Algebra": "Linear Algebra",
  "Linear Algebra": "Abstract Algebra",
  "Number Theory": "Abstract Algebra",
  Probability: "Real Analysis",
  "Logic & Foundations": "Number Theory",
};

export const DECK_IDENTITY = {
  Topology: {
    icon: "T",
    identity: "Space manipulation, global structure, long theorem chains, pathological universe control.",
    colors: ["#44a8ff", "#8b5cf6"],
  },
  "Real Analysis": {
    icon: "R",
    identity: "Precision, limit control, functional pathology, theorem destruction.",
    colors: ["#31dca3", "#ef4444"],
  },
  "Abstract Algebra": {
    icon: "A",
    identity: "Structure combo engine, abstraction escalation, recursive theorem chains, symmetry warfare.",
    colors: ["#c084fc", "#f59e0b"],
  },
  "Linear Algebra": {
    icon: "L",
    identity: "Fast theorem combos, efficient decomposition, stable theorem engines, precision structure control.",
    colors: ["#38bdf8", "#22c55e"],
  },
  "Number Theory": {
    icon: "N",
    identity: "Prime structure, modular traps, arithmetic inevitability, and explosive late theorem finishes.",
    colors: ["#facc15", "#22c55e"],
  },
  Probability: {
    icon: "P",
    identity: "Randomness control, expectation engines, concentration shields, and almost-sure proof lines.",
    colors: ["#34d399", "#38bdf8"],
  },
  "Logic & Foundations": {
    icon: "Ω",
    identity: "Axiom control, consistency pressure, undecidability, and meta-level theorem disruption.",
    colors: ["#c084fc", "#111827"],
  },
};

export const CARD_TYPES = [
  "Definition",
  "Example",
  "Counterexample",
  "Lemma",
  "Proposition",
  "Theorem",
  "Technique",
  "Generalization",
  "Pathology",
  "Meta/Foundation",
];

export const TYPE_STYLE = {
  Definition: { icon: "D", tone: "blue", symbol: "∀" },
  Example: { icon: "E", tone: "green", symbol: "∃" },
  Counterexample: { icon: "C", tone: "red", symbol: "⊥" },
  Lemma: { icon: "L", tone: "purple", symbol: "⇒" },
  Proposition: { icon: "P", tone: "violet", symbol: "⊢" },
  Theorem: { icon: "Th", tone: "gold", symbol: "★" },
  Technique: { icon: "Tx", tone: "teal", symbol: "∴" },
  Generalization: { icon: "G", tone: "silver", symbol: "↥" },
  Pathology: { icon: "X", tone: "orange", symbol: "!" },
  "Meta/Foundation": { icon: "M", tone: "cosmic", symbol: "Ω" },
};

const slug = (value) =>
  value
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const strength = (deck, target, mode) => ({ [target]: mode, [deck]: "native" });

const listPreview = (items = []) => items.slice(0, 3).join(", ");

const describeCard = ({ type, name, description, produces = [], counters = [] }) => {
  if (type === "Example") {
    const produced = produces.length ? ` It gives you proof-state facts: ${listPreview(produces)}.` : "";
    return (
      description ??
      `${name} is a concrete object you can point to while proving. It shows what the surrounding definitions look like in practice.${produced} In gameplay, examples also create a shield that can absorb one compatible counterexample or pathology.`
    );
  }

  if (type === "Counterexample") {
    const targetText = counters.length ? ` It targets assumptions such as ${listPreview(counters)}.` : "";
    const base = description ?? `${name} exposes a place where a proof claim can fail.`;
    return `${base}${targetText} In gameplay, play it during Counter Phase to attack an enemy proof attempt; hard-counter matchups can destroy the attempt, while softer hits usually add a repair requirement.`;
  }

  return description;
};

const card = ({
  deck,
  type,
  name,
  difficulty = 1,
  requirements = [],
  produces,
  counters = [],
  protectsAgainst = [],
  targetDeckStrength = {},
  description,
  flavorText,
  rarity = "common",
}) => ({
  id: `${slug(deck)}-${slug(name)}`,
  name,
  deck,
  type,
  difficulty,
  requirements,
  produces: produces ?? [name],
  counters,
  protectsAgainst,
  targetDeckStrength,
  description: describeCard({ type, name, description, produces: produces ?? [name], counters }),
  flavorText,
  rarity,
});

const definitions = (deck, names) =>
  names.map((name, index) =>
    card({
      deck,
      type: "Definition",
      name,
      difficulty: 0,
      produces: [name],
      description: `Establishes ${name} as a reusable proof-state fact.`,
      flavorText: index % 2 === 0 ? "The duel begins by naming the world." : "A precise word is a loaded spell.",
      rarity: "common",
    })
  );

const examples = (deck, items) =>
  items.map((item) => {
    const producedFacts = item.produces ?? [item.name];
    return card({
      deck,
      type: "Example",
      name: item.name,
      difficulty: item.difficulty ?? 1,
      requirements: item.requirements ?? [],
      produces: producedFacts,
      protectsAgainst: item.protectsAgainst ?? ["Counterexample", "Pathology"],
      description: item.description,
      flavorText: item.flavorText ?? "A single example can hold back a storm of objections.",
      rarity: item.rarity ?? "common",
    });
  });

const techniques = (deck, names) =>
  names.map((name) =>
    card({
      deck,
      type: "Technique",
      name,
      difficulty: 1,
      produces: [name],
      description: `Adds the ${name} technique to your proof toolbox.`,
      flavorText: "A method is a weapon with memory.",
      rarity: "uncommon",
    })
  );

const meta = (deck, names) =>
  names.map((name, index) =>
    card({
      deck,
      type: "Meta/Foundation",
      name,
      difficulty: index > 2 ? 3 : 2,
      produces: [name],
      description: `Escalates the logical setting and unlocks high-complexity chains.`,
      flavorText: "The foundations tilt; the proof adapts or falls.",
      rarity: index > 2 ? "rare" : "uncommon",
    })
  );

export const ALL_CARDS = [
  ...definitions("Topology", [
    "Topological Space",
    "Open Set",
    "Closed Set",
    "Compact",
    "Hausdorff",
    "Connected",
    "Path Connected",
    "Dense Set",
    "Metric Space",
    "Product Topology",
    "Quotient Topology",
    "Normal Space",
    "Simply Connected",
  ]),
  ...examples("Topology", [
    { name: "Euclidean Space", produces: ["Euclidean Space", "Metric Space"] },
    { name: "Unit Interval", produces: ["Unit Interval", "Compact", "Connected"] },
    { name: "Sphere", produces: ["Sphere", "Compact", "Simply Connected"] },
    { name: "Torus", produces: ["Torus", "Product Topology"] },
    { name: "Compact Metric Space", produces: ["Compact Metric Space", "Compact", "Metric Space"] },
    { name: "CW Complex", produces: ["CW Complex", "Path Connected"] },
    { name: "Product Space", produces: ["Product Space", "Product Topology"] },
  ]),
  card({
    deck: "Topology",
    type: "Counterexample",
    name: "Topologist's Sine Curve",
    difficulty: 2,
    produces: ["Connected Pathology"],
    counters: ["connected-to-path-connected assumptions", "naive convergence arguments", "Path Connected"],
    targetDeckStrength: strength("Topology", "Real Analysis", "hard"),
    description: "Breaks attempts that identify connectedness with path connectedness or tame convergence.",
    flavorText: "It approaches forever and arrives nowhere.",
    rarity: "rare",
  }),
  card({
    deck: "Topology",
    type: "Counterexample",
    name: "Non-Metrizable Space",
    difficulty: 2,
    produces: ["Non-Metrizable Context"],
    counters: ["sequence-based proofs", "epsilon-delta methods", "Metric Space"],
    targetDeckStrength: strength("Topology", "Real Analysis", "hard"),
    description: "Punishes arguments that silently replace nets, filters, or covers with sequences.",
    flavorText: "No distance function can save you.",
    rarity: "rare",
  }),
  card({
    deck: "Topology",
    type: "Pathology",
    name: "Long Line",
    difficulty: 3,
    produces: ["Countability Failure"],
    counters: ["countability assumptions", "compactness intuition"],
    targetDeckStrength: strength("Topology", "Real Analysis", "hard"),
    description: "Adds a countability defense requirement to fragile analytic proof attempts.",
    flavorText: "Longer than intuition, stranger than order.",
    rarity: "rare",
  }),
  card({
    deck: "Topology",
    type: "Generalization",
    name: "Infinite Product Space",
    difficulty: 3,
    produces: ["Infinite Product Space"],
    counters: ["simple compactness proofs", "sequential compactness"],
    targetDeckStrength: strength("Topology", "Real Analysis", "hard"),
    description: "Expands the arena until sequential compactness stops looking universal.",
    flavorText: "A product of certainties becomes a universe of choices.",
    rarity: "rare",
  }),
  card({
    deck: "Topology",
    type: "Pathology",
    name: "Dense Topology",
    difficulty: 2,
    produces: ["Dense Topology"],
    counters: ["regularity assumptions", "Dense Set"],
    targetDeckStrength: strength("Topology", "Real Analysis", "hard"),
    description: "Corrupts regularity assumptions in analytic chains.",
    flavorText: "Everywhere is nearby; nowhere is simple.",
    rarity: "uncommon",
  }),
  card({
    deck: "Topology",
    type: "Generalization",
    name: "Infinite-Dimensional Topology",
    difficulty: 2,
    produces: ["Infinite-Dimensional Context"],
    counters: ["spectral theorem", "basis arguments", "diagonalization"],
    targetDeckStrength: strength("Topology", "Linear Algebra", "soft"),
    description: "Soft-attacks finite-dimensional linear arguments by adding a topology requirement.",
    flavorText: "The basis thins out into mist.",
    rarity: "uncommon",
  }),
  card({
    deck: "Topology",
    type: "Pathology",
    name: "Wild Quotient Space",
    difficulty: 2,
    produces: ["Wild Quotient Space"],
    counters: ["clean symmetry decomposition"],
    targetDeckStrength: strength("Topology", "Abstract Algebra", "soft"),
    description: "Weakens clean symmetry decompositions and forces quotient defenses.",
    flavorText: "Identify too much, and structure screams.",
    rarity: "uncommon",
  }),
  card({
    deck: "Topology",
    type: "Lemma",
    name: "Tube Lemma",
    difficulty: 2,
    requirements: ["Product Topology", "Compact"],
    produces: ["Tube Lemma", "Product Control"],
    description: "Turns compact fibers into local product control.",
    flavorText: "A small neighborhood, held open by compactness.",
    rarity: "uncommon",
  }),
  card({
    deck: "Topology",
    type: "Lemma",
    name: "Finite Intersection Property",
    difficulty: 2,
    requirements: ["Closed Set", "Compact"],
    produces: ["Finite Intersection Property", "Compactness Criterion"],
    description: "Converts closed-set pressure into a compactness criterion.",
    flavorText: "Every finite clash survives; the infinite one must answer.",
    rarity: "uncommon",
  }),
  card({
    deck: "Topology",
    type: "Lemma",
    name: "Compact Subcover Lemma",
    difficulty: 1,
    requirements: ["Open Set", "Compact"],
    produces: ["Compact Subcover Lemma", "Finite Subcover"],
    description: "Extracts a finite subcover from an open cover.",
    flavorText: "Infinite cover, finite verdict.",
    rarity: "common",
  }),
  card({
    deck: "Topology",
    type: "Lemma",
    name: "Path Lifting Lemma",
    difficulty: 2,
    requirements: ["Path Connected", "Quotient Topology"],
    produces: ["Path Lifting Lemma", "Lifted Path"],
    description: "Lifts path structure through controlled quotient maps.",
    flavorText: "Follow the path where the space forgot itself.",
    rarity: "uncommon",
  }),
  card({
    deck: "Topology",
    type: "Proposition",
    name: "Path Connected Implies Connected",
    difficulty: 2,
    requirements: ["Path Connected"],
    produces: ["Path Connected Implies Connected", "Connected"],
    description: "Turns path control into global connectedness.",
    flavorText: "A path is a promise the space keeps.",
    rarity: "uncommon",
  }),
  card({
    deck: "Topology",
    type: "Proposition",
    name: "Compact Subsets of Hausdorff Are Closed",
    difficulty: 2,
    requirements: ["Compact", "Hausdorff"],
    produces: ["Compact Subsets of Hausdorff Are Closed", "Closed Set"],
    description: "Makes compactness visible through Hausdorff separation.",
    flavorText: "Separation sharpens compact shadows into closed sets.",
    rarity: "uncommon",
  }),
  card({
    deck: "Topology",
    type: "Proposition",
    name: "Closed Subset of Compact Is Compact",
    difficulty: 2,
    requirements: ["Closed Set", "Compact"],
    produces: ["Closed Subset of Compact Is Compact", "Compact"],
    description: "Preserves compactness through closed subspaces.",
    flavorText: "A closed door keeps the finite subcover inside.",
    rarity: "uncommon",
  }),
  card({
    deck: "Topology",
    type: "Proposition",
    name: "Continuous Image of Connected Is Connected",
    difficulty: 2,
    requirements: ["Connected", "Topological Space"],
    produces: ["Continuous Image of Connected Is Connected", "Connected Image"],
    description: "Pushes connectedness through continuous maps.",
    flavorText: "A continuous image does not tear the argument apart.",
    rarity: "uncommon",
  }),
  ...techniques("Topology", ["Open Cover Argument", "Separation Argument", "Compactness Extraction", "Glueing Argument"]),
  ...meta("Topology", ["Weak Topology", "Infinite-Dimensional Context", "Non-Paracompact Setting", "Fractal Boundary", "Choice-Dependent Construction"]),
  card({
    deck: "Topology",
    type: "Theorem",
    name: "Tychonoff Theorem",
    difficulty: 5,
    requirements: ["Product Topology", "Compact", "Choice-Dependent Construction"],
    produces: ["Tychonoff Theorem", "Product Compactness"],
    description: "Proves arbitrary products of compact spaces are compact.",
    flavorText: "The axiom of choice signs the treaty between infinitely many compact worlds.",
    rarity: "legendary",
  }),
  card({
    deck: "Topology",
    type: "Theorem",
    name: "Brouwer Fixed Point Theorem",
    difficulty: 4,
    requirements: ["Compact", "Euclidean Space", "Open Cover Argument"],
    produces: ["Brouwer Fixed Point Theorem", "Fixed Point"],
    description: "Forces a continuous self-map of a disk to hold at least one point still.",
    flavorText: "Every motion leaves a witness.",
    rarity: "legendary",
  }),
  card({
    deck: "Topology",
    type: "Theorem",
    name: "Urysohn Lemma",
    difficulty: 4,
    requirements: ["Normal Space", "Closed Set", "Separation Argument"],
    produces: ["Urysohn Lemma", "Separation Function"],
    description: "Separates closed sets by a continuous function.",
    flavorText: "Between disjoint closed sets, a function builds a bridge of values.",
    rarity: "rare",
  }),
  card({
    deck: "Topology",
    type: "Theorem",
    name: "Jordan Curve Theorem",
    difficulty: 5,
    requirements: ["Sphere", "Simply Connected", "Glueing Argument"],
    produces: ["Jordan Curve Theorem", "Planar Separation"],
    description: "A simple closed curve separates the plane into inside and outside.",
    flavorText: "One loop, two worlds.",
    rarity: "legendary",
  }),
  card({
    deck: "Topology",
    type: "Theorem",
    name: "Compact Hausdorff Implies Normal",
    difficulty: 3,
    requirements: ["Compact", "Hausdorff"],
    produces: ["Compact Hausdorff Implies Normal", "Normal Space"],
    description: "Compactness and Hausdorff separation combine into normality.",
    flavorText: "Finite subcovers do the quiet work of separation.",
    rarity: "rare",
  }),

  ...definitions("Real Analysis", [
    "Convergence",
    "Uniform Convergence",
    "Continuity",
    "Differentiability",
    "Integrability",
    "Cauchy Sequence",
    "Completeness",
    "Measurable Function",
    "Lipschitz Continuity",
  ]),
  ...examples("Real Analysis", [
    { name: "Polynomial Function", produces: ["Polynomial Function", "Continuity", "Differentiability"] },
    { name: "Smooth Function", produces: ["Smooth Function", "Differentiability"] },
    { name: "Gaussian Function", produces: ["Gaussian Function", "Integrability"] },
    { name: "Step Function", produces: ["Step Function", "Measurable Function"] },
    { name: "Fourier Series", produces: ["Fourier Series", "Convergence"] },
    { name: "Monotone Sequence", produces: ["Monotone Sequence", "Convergence"] },
  ]),
  card({
    deck: "Real Analysis",
    type: "Counterexample",
    name: "Weierstrass Function",
    difficulty: 2,
    produces: ["Nowhere Differentiable Function"],
    counters: ["smoothness assumptions", "Differentiability"],
    targetDeckStrength: strength("Real Analysis", "Topology", "hard"),
    description: "Destroys smoothness intuition in geometric chains.",
    flavorText: "Continuous everywhere, tame nowhere.",
    rarity: "rare",
  }),
  card({
    deck: "Real Analysis",
    type: "Counterexample",
    name: "Dirichlet Function",
    difficulty: 2,
    produces: ["Everywhere Discontinuous Function"],
    counters: ["continuity intuition", "Continuity"],
    targetDeckStrength: strength("Real Analysis", "Topology", "hard"),
    description: "Turns density into a continuity trap.",
    flavorText: "Rationals and irrationals refuse to reconcile.",
    rarity: "rare",
  }),
  card({
    deck: "Real Analysis",
    type: "Pathology",
    name: "Nonuniform Convergence",
    difficulty: 2,
    produces: ["Nonuniform Convergence"],
    counters: ["limit interchange", "Uniform Convergence"],
    targetDeckStrength: strength("Real Analysis", "Topology", "hard"),
    description: "Adds a uniformity defense to fragile limit arguments.",
    flavorText: "Pointwise promises do not bind the whole domain.",
    rarity: "uncommon",
  }),
  card({
    deck: "Real Analysis",
    type: "Counterexample",
    name: "Oscillatory Sequence",
    difficulty: 2,
    produces: ["Oscillation"],
    counters: ["compactness extraction", "Convergence"],
    targetDeckStrength: strength("Real Analysis", "Topology", "hard"),
    description: "Undermines compactness extractions with violent oscillation.",
    flavorText: "Every subsequence hears a different rhythm.",
    rarity: "uncommon",
  }),
  card({
    deck: "Real Analysis",
    type: "Pathology",
    name: "Dense Discontinuity",
    difficulty: 2,
    produces: ["Dense Discontinuity"],
    counters: ["topological regularity", "Continuity"],
    targetDeckStrength: strength("Real Analysis", "Topology", "hard"),
    description: "Places discontinuities everywhere a clean topological proof wants air.",
    flavorText: "No interval is safe.",
    rarity: "rare",
  }),
  card({
    deck: "Real Analysis",
    type: "Pathology",
    name: "Singular Measure",
    difficulty: 3,
    produces: ["Singular Measure"],
    counters: ["geometric intuition", "Measurable Function"],
    targetDeckStrength: strength("Real Analysis", "Topology", "hard"),
    description: "Turns geometric intuition into measure-theoretic ambiguity.",
    flavorText: "Mass gathers where length sees almost nothing.",
    rarity: "rare",
  }),
  card({
    deck: "Real Analysis",
    type: "Generalization",
    name: "Banach Space Explosion",
    difficulty: 2,
    produces: ["Banach Space Context"],
    counters: ["finite-dimensional theorems"],
    targetDeckStrength: strength("Real Analysis", "Linear Algebra", "soft"),
    description: "Soft-attacks finite-dimensional linear results by forcing Banach-space context.",
    flavorText: "Linear intuition meets infinite analytic depth.",
    rarity: "uncommon",
  }),
  card({
    deck: "Real Analysis",
    type: "Generalization",
    name: "Nonconstructive Limit",
    difficulty: 2,
    produces: ["Nonconstructive Limit"],
    counters: ["purely existential arguments"],
    targetDeckStrength: strength("Real Analysis", "Abstract Algebra", "soft"),
    description: "Weakens explicit algebraic construction by introducing a limiting existence layer.",
    flavorText: "The object exists, but the route vanishes.",
    rarity: "uncommon",
  }),
  card({
    deck: "Real Analysis",
    type: "Lemma",
    name: "Cauchy Criterion",
    difficulty: 2,
    requirements: ["Cauchy Sequence", "Completeness"],
    produces: ["Cauchy Criterion", "Convergence"],
    description: "Converts Cauchy control into convergence under completeness.",
    flavorText: "Eventually close becomes finally certain.",
    rarity: "common",
  }),
  card({
    deck: "Real Analysis",
    type: "Lemma",
    name: "Dominated Estimate",
    difficulty: 2,
    requirements: ["Integrability", "Measurable Function"],
    produces: ["Dominated Estimate", "Dominated Bound"],
    description: "Pins a moving function sequence under an integrable ceiling.",
    flavorText: "A ceiling can be a theorem's floor.",
    rarity: "uncommon",
  }),
  card({
    deck: "Real Analysis",
    type: "Lemma",
    name: "Arzela-Ascoli Setup",
    difficulty: 3,
    requirements: ["Continuity", "Compactness Extraction"],
    produces: ["Arzela-Ascoli Setup", "Equicontinuity"],
    description: "Builds the compactness frame for function families.",
    flavorText: "Control the wiggle; claim the subsequence.",
    rarity: "rare",
  }),
  card({
    deck: "Real Analysis",
    type: "Lemma",
    name: "Epsilon Control Lemma",
    difficulty: 1,
    requirements: ["Convergence"],
    produces: ["Epsilon Control Lemma", "Epsilon Control"],
    description: "Transforms eventual convergence into explicit epsilon control.",
    flavorText: "The duel narrows to an epsilon and a choice of N.",
    rarity: "common",
  }),
  card({
    deck: "Real Analysis",
    type: "Proposition",
    name: "Continuous on Compact Implies Bounded",
    difficulty: 2,
    requirements: ["Continuity", "Compactness Extraction"],
    produces: ["Continuous on Compact Implies Bounded", "Bounded Function"],
    description: "Uses compactness to trap a continuous function in a finite range.",
    flavorText: "A compact domain lets no value run away.",
    rarity: "uncommon",
  }),
  card({
    deck: "Real Analysis",
    type: "Proposition",
    name: "Uniform Convergence Preserves Continuity",
    difficulty: 2,
    requirements: ["Uniform Convergence", "Continuity"],
    produces: ["Uniform Convergence Preserves Continuity", "Continuity"],
    description: "Carries continuity through a uniform limiting process.",
    flavorText: "Uniformity keeps the limit honest.",
    rarity: "uncommon",
  }),
  card({
    deck: "Real Analysis",
    type: "Proposition",
    name: "Monotone Bounded Sequences Converge",
    difficulty: 2,
    requirements: ["Monotone Sequence", "Completeness"],
    produces: ["Monotone Bounded Sequences Converge", "Convergence"],
    description: "Turns monotone bounded motion into a limit.",
    flavorText: "An ordered climb finds its ceiling.",
    rarity: "uncommon",
  }),
  ...techniques("Real Analysis", ["Epsilon-Delta Attack", "Diagonalization", "Approximation Argument", "Compactness Extraction"]),
  ...meta("Real Analysis", ["Weak Convergence", "Infinite Measure Space", "Banach Space Context", "Distributional Framework", "Nonmeasurable Set"]),
  card({
    deck: "Real Analysis",
    type: "Theorem",
    name: "Arzela-Ascoli Theorem",
    difficulty: 5,
    requirements: ["Arzela-Ascoli Setup", "Equicontinuity", "Compactness Extraction"],
    produces: ["Arzela-Ascoli Theorem", "Compact Function Family"],
    description: "Extracts convergent subsequences from controlled function families.",
    flavorText: "A family of functions becomes compact when its oscillations learn restraint.",
    rarity: "legendary",
  }),
  card({
    deck: "Real Analysis",
    type: "Theorem",
    name: "Stone-Weierstrass Theorem",
    difficulty: 5,
    requirements: ["Polynomial Function", "Approximation Argument", "Continuity"],
    produces: ["Stone-Weierstrass Theorem", "Uniform Approximation"],
    description: "Approximates continuous functions by a powerful algebra of simple functions.",
    flavorText: "Polynomials learn every continuous shape by degrees.",
    rarity: "legendary",
  }),
  card({
    deck: "Real Analysis",
    type: "Theorem",
    name: "Hahn-Banach Theorem",
    difficulty: 5,
    requirements: ["Banach Space Context", "Weak Convergence"],
    produces: ["Hahn-Banach Theorem", "Functional Extension"],
    description: "Extends bounded linear functionals beyond their starting domain.",
    flavorText: "A functional crosses the boundary without losing its norm.",
    rarity: "legendary",
  }),
  card({
    deck: "Real Analysis",
    type: "Theorem",
    name: "Dominated Convergence Theorem",
    difficulty: 4,
    requirements: ["Dominated Estimate", "Measurable Function", "Convergence"],
    produces: ["Dominated Convergence Theorem", "Limit Integral Swap"],
    description: "Safely interchanges limits and integrals under domination.",
    flavorText: "The limit passes beneath a watchful bound.",
    rarity: "rare",
  }),
  card({
    deck: "Real Analysis",
    type: "Theorem",
    name: "Open Mapping Theorem",
    difficulty: 4,
    requirements: ["Completeness", "Banach Space Context", "Epsilon Control Lemma"],
    produces: ["Open Mapping Theorem", "Open Linear Image"],
    description: "Shows surjective bounded linear maps between Banach spaces are open.",
    flavorText: "Surjectivity opens the door all the way.",
    rarity: "rare",
  }),

  ...definitions("Abstract Algebra", [
    "Group",
    "Ring",
    "Field",
    "Ideal",
    "Module",
    "Homomorphism",
    "Quotient Group",
    "PID",
    "Exact Sequence",
  ]),
  ...examples("Abstract Algebra", [
    { name: "Integers", produces: ["Integers", "Ring", "PID"] },
    { name: "Cyclic Group", produces: ["Cyclic Group", "Group"] },
    { name: "Symmetric Group", produces: ["Symmetric Group", "Group"] },
    { name: "Polynomial Ring", produces: ["Polynomial Ring", "Ring"] },
    { name: "Quaternion Group", produces: ["Quaternion Group", "Group"] },
    { name: "Finite Field", produces: ["Finite Field", "Field"] },
  ]),
  card({
    deck: "Abstract Algebra",
    type: "Counterexample",
    name: "Noncommutative Ring",
    difficulty: 2,
    produces: ["Noncommutative Ring"],
    counters: ["matrix simplifications", "determinant arguments", "Commutativity"],
    targetDeckStrength: strength("Abstract Algebra", "Linear Algebra", "hard"),
    description: "Breaks linear arguments that smuggle in commutativity.",
    flavorText: "Multiplication changes its mind when order matters.",
    rarity: "rare",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Generalization",
    name: "Infinite-Dimensional Module",
    difficulty: 2,
    produces: ["Infinite-Dimensional Module"],
    counters: ["basis methods", "Basis"],
    targetDeckStrength: strength("Abstract Algebra", "Linear Algebra", "hard"),
    description: "Turns vector-space basis comfort into module-theoretic uncertainty.",
    flavorText: "A module is not obliged to behave like a vector space.",
    rarity: "rare",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Pathology",
    name: "Wild Representation Type",
    difficulty: 3,
    produces: ["Wild Representation Type"],
    counters: ["classification theorems", "Diagonalizable"],
    targetDeckStrength: strength("Abstract Algebra", "Linear Algebra", "hard"),
    description: "Adds classification chaos to decomposition chains.",
    flavorText: "There are too many shapes to name.",
    rarity: "rare",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Pathology",
    name: "Torsion Pathology",
    difficulty: 2,
    produces: ["Torsion Pathology"],
    counters: ["vector-space intuition", "Rank"],
    targetDeckStrength: strength("Abstract Algebra", "Linear Algebra", "hard"),
    description: "Undermines rank and independence intuitions with torsion.",
    flavorText: "Repeated addition folds the world back on itself.",
    rarity: "uncommon",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Pathology",
    name: "Non-Noetherian Ring",
    difficulty: 3,
    produces: ["Non-Noetherian Ring"],
    counters: ["finiteness arguments", "Finite-Dimensional Constraint"],
    targetDeckStrength: strength("Abstract Algebra", "Linear Algebra", "hard"),
    description: "Forces infinite ascending complexity into finiteness-based proofs.",
    flavorText: "The chain refuses to stop.",
    rarity: "rare",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Generalization",
    name: "Derived Category Shift",
    difficulty: 4,
    produces: ["Derived Setting"],
    counters: ["classification theorems", "basis methods"],
    targetDeckStrength: strength("Abstract Algebra", "Linear Algebra", "hard"),
    description: "Late-game escalation that adds a homological requirement to enemy theorem attempts.",
    flavorText: "The proof moves one degree higher and the board goes quiet.",
    rarity: "legendary",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Generalization",
    name: "Infinite Symmetry Group",
    difficulty: 2,
    produces: ["Infinite Symmetry Group"],
    counters: ["geometric decomposition"],
    targetDeckStrength: strength("Abstract Algebra", "Topology", "soft"),
    description: "Soft-attacks geometric decompositions with excessive symmetry.",
    flavorText: "Symmetry multiplies until geometry loses its preferred angle.",
    rarity: "uncommon",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Generalization",
    name: "Nonconstructive Quotient",
    difficulty: 2,
    produces: ["Nonconstructive Quotient"],
    counters: ["explicit construction arguments"],
    targetDeckStrength: strength("Abstract Algebra", "Real Analysis", "soft"),
    description: "Soft-attacks explicit analytic construction by quotienting away representatives.",
    flavorText: "The class exists; the representative negotiates.",
    rarity: "uncommon",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Lemma",
    name: "Orbit-Stabilizer",
    difficulty: 2,
    requirements: ["Group"],
    produces: ["Orbit-Stabilizer", "Group Action"],
    description: "Turns a group action into a counting engine.",
    flavorText: "Every orbit pays its stabilizer.",
    rarity: "uncommon",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Lemma",
    name: "Coset Lemma",
    difficulty: 1,
    requirements: ["Group", "Quotient Group"],
    produces: ["Coset Lemma", "Coset Control"],
    description: "Controls quotient behavior through cosets.",
    flavorText: "A subgroup casts equal shadows.",
    rarity: "common",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Lemma",
    name: "Euclidean Algorithm",
    difficulty: 1,
    requirements: ["PID"],
    produces: ["Euclidean Algorithm", "Bezout Identity"],
    description: "Extracts Bezout-style structure from principal ideal domains.",
    flavorText: "Division repeats until structure is revealed.",
    rarity: "common",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Lemma",
    name: "Exactness Lemma",
    difficulty: 2,
    requirements: ["Exact Sequence", "Homomorphism"],
    produces: ["Exactness Lemma", "Kernel Image Control"],
    description: "Tracks kernels and images through an exact sequence.",
    flavorText: "What leaves one map enters the next.",
    rarity: "uncommon",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Proposition",
    name: "Kernels Are Normal",
    difficulty: 2,
    requirements: ["Homomorphism", "Group"],
    produces: ["Kernels Are Normal", "Normal Subgroup"],
    description: "Converts homomorphism kernels into normal subgroups.",
    flavorText: "The kernel knows every conjugate by name.",
    rarity: "uncommon",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Proposition",
    name: "Finite Integral Domains Are Fields",
    difficulty: 2,
    requirements: ["Field", "Ring"],
    produces: ["Finite Integral Domains Are Fields", "Field"],
    description: "Promotes finite domain structure into field structure.",
    flavorText: "Finiteness turns cancellation into inverses.",
    rarity: "uncommon",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Proposition",
    name: "Subgroups of Cyclic Groups Are Cyclic",
    difficulty: 2,
    requirements: ["Cyclic Group", "Group"],
    produces: ["Subgroups of Cyclic Groups Are Cyclic", "Cyclic Structure"],
    description: "Keeps cyclic structure through subgroups.",
    flavorText: "One generator leaves descendants.",
    rarity: "uncommon",
  }),
  ...techniques("Abstract Algebra", ["Diagram Chase", "Quotient Construction", "Universal Property", "Localization"]),
  ...meta("Abstract Algebra", ["Infinite Group", "Arbitrary Module", "Higher Algebra Context", "Derived Setting", "Choice-Based Construction"]),
  card({
    deck: "Abstract Algebra",
    type: "Theorem",
    name: "Sylow Theorems",
    difficulty: 4,
    requirements: ["Group", "Orbit-Stabilizer", "Group Action"],
    produces: ["Sylow Theorems", "p-Subgroup Control"],
    description: "Controls subgroups of prime-power order inside finite groups.",
    flavorText: "Prime powers hide inside every finite symmetry.",
    rarity: "legendary",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Theorem",
    name: "Chinese Remainder Theorem",
    difficulty: 3,
    requirements: ["Ring", "Ideal", "Euclidean Algorithm"],
    produces: ["Chinese Remainder Theorem", "Modular Decomposition"],
    description: "Splits compatible modular data into a single solution.",
    flavorText: "Many clocks agree on one time.",
    rarity: "rare",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Theorem",
    name: "Structure Theorem for Modules",
    difficulty: 5,
    requirements: ["Module", "PID", "Localization"],
    produces: ["Structure Theorem for Modules", "Module Decomposition"],
    description: "Decomposes finitely generated modules over a PID.",
    flavorText: "Structure appears when the ring is disciplined.",
    rarity: "legendary",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Theorem",
    name: "Cayley's Theorem",
    difficulty: 3,
    requirements: ["Group", "Symmetric Group", "Homomorphism"],
    produces: ["Cayley's Theorem", "Permutation Realization"],
    description: "Realizes every group as a permutation group.",
    flavorText: "Every group can move something.",
    rarity: "rare",
  }),
  card({
    deck: "Abstract Algebra",
    type: "Theorem",
    name: "Isomorphism Theorems",
    difficulty: 4,
    requirements: ["Homomorphism", "Quotient Group", "Kernels Are Normal"],
    produces: ["Isomorphism Theorems", "Quotient Equivalence"],
    description: "Relates quotients, kernels, and images across homomorphisms.",
    flavorText: "Different doors open onto the same structure.",
    rarity: "legendary",
  }),

  ...definitions("Linear Algebra", [
    "Vector Space",
    "Basis",
    "Linear Map",
    "Eigenvector",
    "Rank",
    "Kernel",
    "Inner Product",
    "Orthogonality",
    "Diagonalizable",
  ]),
  ...examples("Linear Algebra", [
    { name: "Euclidean Space", produces: ["Euclidean Space", "Vector Space", "Inner Product"] },
    { name: "Orthogonal Basis", produces: ["Orthogonal Basis", "Basis", "Orthogonality"] },
    { name: "Symmetric Matrix", produces: ["Symmetric Matrix", "Linear Map", "Diagonalizable"] },
    { name: "Rotation Matrix", produces: ["Rotation Matrix", "Linear Map"] },
    { name: "Polynomial Vector Space", produces: ["Polynomial Vector Space", "Vector Space"] },
  ]),
  card({
    deck: "Linear Algebra",
    type: "Counterexample",
    name: "Matrix Realization",
    difficulty: 2,
    produces: ["Matrix Realization"],
    counters: ["abstract algebra objects", "abstraction bonuses"],
    targetDeckStrength: strength("Linear Algebra", "Abstract Algebra", "hard"),
    description: "Forces abstract algebraic objects into concrete matrices and weakens abstraction bonuses.",
    flavorText: "Write it as a matrix and watch the mystery lose a dimension.",
    rarity: "rare",
  }),
  card({
    deck: "Linear Algebra",
    type: "Generalization",
    name: "Finite-Dimensional Constraint",
    difficulty: 2,
    produces: ["Finite-Dimensional Constraint"],
    counters: ["infinite algebraic escalation"],
    targetDeckStrength: strength("Linear Algebra", "Abstract Algebra", "hard"),
    description: "Cuts off infinite algebraic escalation by forcing finite-dimensional hypotheses.",
    flavorText: "Count the basis vectors. Then count them again.",
    rarity: "uncommon",
  }),
  card({
    deck: "Linear Algebra",
    type: "Pathology",
    name: "Coordinate Collapse",
    difficulty: 2,
    produces: ["Coordinate Collapse"],
    counters: ["category-style theorem chains"],
    targetDeckStrength: strength("Linear Algebra", "Abstract Algebra", "hard"),
    description: "Weakens high-abstraction chains by imposing coordinate-level constraints.",
    flavorText: "The diagram descends into coordinates.",
    rarity: "rare",
  }),
  card({
    deck: "Linear Algebra",
    type: "Counterexample",
    name: "Defective Matrix",
    difficulty: 2,
    produces: ["Defective Matrix"],
    counters: ["decomposition assumptions", "Diagonalizable"],
    targetDeckStrength: strength("Linear Algebra", "Abstract Algebra", "hard"),
    description: "Counters decomposition assumptions by withholding enough eigenvectors.",
    flavorText: "The eigenvalues arrive without their full entourage.",
    rarity: "rare",
  }),
  card({
    deck: "Linear Algebra",
    type: "Counterexample",
    name: "Singular Operator",
    difficulty: 2,
    produces: ["Singular Operator"],
    counters: ["invertibility chains", "Kernel"],
    targetDeckStrength: strength("Linear Algebra", "Abstract Algebra", "hard"),
    description: "Breaks invertibility chains with nontrivial kernel pressure.",
    flavorText: "Some directions vanish forever.",
    rarity: "uncommon",
  }),
  card({
    deck: "Linear Algebra",
    type: "Pathology",
    name: "Spectral Collapse",
    difficulty: 3,
    produces: ["Spectral Collapse"],
    counters: ["unstable algebraic theorem combos", "Eigenvector"],
    targetDeckStrength: strength("Linear Algebra", "Abstract Algebra", "hard"),
    description: "Destroys unstable algebraic theorem combos with spectral failure.",
    flavorText: "The spectrum folds in on the proof.",
    rarity: "legendary",
  }),
  card({
    deck: "Linear Algebra",
    type: "Generalization",
    name: "Infinite Rank Operator",
    difficulty: 2,
    produces: ["Infinite Rank Operator"],
    counters: ["compactness intuition"],
    targetDeckStrength: strength("Linear Algebra", "Topology", "soft"),
    description: "Soft-attacks topological compactness intuition with infinite-rank behavior.",
    flavorText: "Rank stretches past every finite comfort.",
    rarity: "uncommon",
  }),
  card({
    deck: "Linear Algebra",
    type: "Pathology",
    name: "Spectral Instability",
    difficulty: 2,
    produces: ["Spectral Instability"],
    counters: ["convergence-based spectral arguments"],
    targetDeckStrength: strength("Linear Algebra", "Real Analysis", "soft"),
    description: "Soft-attacks convergence-based spectral proofs.",
    flavorText: "The eigenvalues drift exactly when you need them still.",
    rarity: "uncommon",
  }),
  card({
    deck: "Linear Algebra",
    type: "Lemma",
    name: "Gram-Schmidt",
    difficulty: 2,
    requirements: ["Basis", "Inner Product"],
    produces: ["Gram-Schmidt", "Orthogonal Basis", "Orthogonality"],
    description: "Turns a basis into an orthogonal basis under an inner product.",
    flavorText: "One vector at a time, the angles learn discipline.",
    rarity: "uncommon",
  }),
  card({
    deck: "Linear Algebra",
    type: "Lemma",
    name: "Basis Extension Lemma",
    difficulty: 1,
    requirements: ["Vector Space", "Basis"],
    produces: ["Basis Extension Lemma", "Extended Basis"],
    description: "Extends independent structure into a full basis.",
    flavorText: "Incomplete independence becomes a coordinate system.",
    rarity: "common",
  }),
  card({
    deck: "Linear Algebra",
    type: "Lemma",
    name: "Kernel-Image Lemma",
    difficulty: 2,
    requirements: ["Linear Map", "Kernel"],
    produces: ["Kernel-Image Lemma", "Image Control"],
    description: "Tracks the relation between kernel behavior and image structure.",
    flavorText: "What disappears explains what remains.",
    rarity: "uncommon",
  }),
  card({
    deck: "Linear Algebra",
    type: "Lemma",
    name: "Orthogonal Projection Lemma",
    difficulty: 2,
    requirements: ["Inner Product", "Orthogonality"],
    produces: ["Orthogonal Projection Lemma", "Projection Control"],
    description: "Controls components along orthogonal subspaces.",
    flavorText: "The vector confesses its shadows.",
    rarity: "uncommon",
  }),
  card({
    deck: "Linear Algebra",
    type: "Proposition",
    name: "Rank-Nullity",
    difficulty: 2,
    requirements: ["Linear Map", "Kernel"],
    produces: ["Rank-Nullity", "Rank", "Image Control"],
    description: "Balances rank and nullity for a linear map.",
    flavorText: "Dimension is conserved through loss and image.",
    rarity: "rare",
  }),
  card({
    deck: "Linear Algebra",
    type: "Proposition",
    name: "Distinct Eigenvectors Are Independent",
    difficulty: 2,
    requirements: ["Eigenvector", "Linear Map"],
    produces: ["Distinct Eigenvectors Are Independent", "Independent Eigenvectors"],
    description: "Builds independence from distinct eigenvalues.",
    flavorText: "Different eigenvalues refuse the same dependence.",
    rarity: "uncommon",
  }),
  card({
    deck: "Linear Algebra",
    type: "Proposition",
    name: "Orthogonal Complements Are Subspaces",
    difficulty: 2,
    requirements: ["Orthogonality", "Vector Space"],
    produces: ["Orthogonal Complements Are Subspaces", "Subspace"],
    description: "Makes orthogonal complements usable as subspaces.",
    flavorText: "The perpendicular world is still a world.",
    rarity: "uncommon",
  }),
  ...techniques("Linear Algebra", ["Matrix Reduction", "Basis Change", "Orthogonalization", "Spectral Decomposition"]),
  ...meta("Linear Algebra", ["Infinite-Dimensional Space", "Banach Space Context", "Unbounded Operator", "Degenerate Bilinear Form"]),
  card({
    deck: "Linear Algebra",
    type: "Theorem",
    name: "Spectral Theorem",
    difficulty: 5,
    requirements: ["Symmetric Matrix", "Orthogonal Basis", "Spectral Decomposition"],
    produces: ["Spectral Theorem", "Orthogonal Diagonalization"],
    description: "Diagonalizes self-adjoint structure through orthogonal coordinates.",
    flavorText: "A symmetric operator speaks in perpendicular eigenvectors.",
    rarity: "legendary",
  }),
  card({
    deck: "Linear Algebra",
    type: "Theorem",
    name: "Singular Value Decomposition",
    difficulty: 4,
    requirements: ["Linear Map", "Orthogonalization", "Matrix Reduction"],
    produces: ["Singular Value Decomposition", "SVD Factors"],
    description: "Factors a linear map into orthogonal directions and singular scales.",
    flavorText: "Every matrix reveals its stretch, turn, and shadow.",
    rarity: "legendary",
  }),
  card({
    deck: "Linear Algebra",
    type: "Theorem",
    name: "Jordan Canonical Form",
    difficulty: 5,
    requirements: ["Eigenvector", "Basis Change", "Matrix Reduction"],
    produces: ["Jordan Canonical Form", "Jordan Decomposition"],
    description: "Classifies linear maps up to a structured canonical form.",
    flavorText: "When diagonalization fails, Jordan keeps the ledger.",
    rarity: "legendary",
  }),
  card({
    deck: "Linear Algebra",
    type: "Theorem",
    name: "Cayley-Hamilton",
    difficulty: 4,
    requirements: ["Linear Map", "Matrix Reduction", "Polynomial Vector Space"],
    produces: ["Cayley-Hamilton", "Characteristic Identity"],
    description: "Shows every matrix satisfies its own characteristic polynomial.",
    flavorText: "The matrix is bound by the polynomial it casts.",
    rarity: "rare",
  }),
  card({
    deck: "Linear Algebra",
    type: "Theorem",
    name: "Rank-Nullity Theorem",
    difficulty: 3,
    requirements: ["Rank-Nullity", "Vector Space"],
    produces: ["Rank-Nullity Theorem", "Dimension Balance"],
    description: "Promotes rank-nullity into a theorem-level engine.",
    flavorText: "Nothing is lost; it is counted in the kernel.",
    rarity: "rare",
  }),
  ...definitions("Number Theory", [
    "Divisibility",
    "Prime",
    "Congruence",
    "Modular Arithmetic",
    "Coprime",
    "Residue Class",
    "Multiplicative Group",
    "Arithmetic Function",
    "Quadratic Residue",
  ]),
  ...examples("Number Theory", [
    { name: "Integers Mod n", produces: ["Integers Mod n", "Modular Arithmetic", "Residue Class"] },
    { name: "Prime Field", produces: ["Prime Field", "Prime", "Multiplicative Group"] },
    { name: "Fibonacci Sequence", produces: ["Fibonacci Sequence", "Recurrence"] },
    { name: "Gaussian Integers", produces: ["Gaussian Integers", "Unique Factorization Domain"] },
    { name: "Unit Group", produces: ["Unit Group", "Multiplicative Group"] },
    { name: "Quadratic Residue Example", produces: ["Quadratic Residue Example", "Quadratic Residue"] },
  ]),
  card({
    deck: "Number Theory",
    type: "Counterexample",
    name: "Carmichael Number",
    difficulty: 2,
    produces: ["Pseudoprime Trap"],
    counters: ["prime-test intuition", "group order shortcuts", "Prime"],
    targetDeckStrength: strength("Number Theory", "Abstract Algebra", "hard"),
    description: "Punishes algebraic proofs that assume Fermat behavior characterizes primes.",
    flavorText: "It passes the test and still lies.",
    rarity: "rare",
  }),
  card({
    deck: "Number Theory",
    type: "Pathology",
    name: "Unique Factorization Failure",
    difficulty: 3,
    produces: ["Factorization Obstruction"],
    counters: ["clean ideal decomposition", "PID"],
    targetDeckStrength: strength("Number Theory", "Abstract Algebra", "hard"),
    description: "Breaks algebraic arguments that quietly rely on unique factorization.",
    flavorText: "The factors disagree about the past.",
    rarity: "rare",
  }),
  card({
    deck: "Number Theory",
    type: "Generalization",
    name: "p-adic World",
    difficulty: 2,
    produces: ["p-adic Context"],
    counters: ["real limit intuition", "Continuity"],
    targetDeckStrength: strength("Number Theory", "Real Analysis", "soft"),
    description: "Moves the proof into a valuation geometry where closeness means divisibility.",
    flavorText: "Numbers approach by sharing deeper powers.",
    rarity: "uncommon",
  }),
  card({
    deck: "Number Theory",
    type: "Pathology",
    name: "Large Prime Gap",
    difficulty: 2,
    produces: ["Prime Gap"],
    counters: ["uniform distribution intuition"],
    targetDeckStrength: strength("Number Theory", "Probability", "soft"),
    description: "Disrupts probabilistic smoothness assumptions about prime occurrence.",
    flavorText: "The primes go silent for a while.",
    rarity: "uncommon",
  }),
  card({
    deck: "Number Theory",
    type: "Lemma",
    name: "Euclid's Lemma",
    difficulty: 2,
    requirements: ["Prime", "Divisibility"],
    produces: ["Euclid's Lemma", "Prime Divisibility"],
    description: "A prime dividing a product must divide one factor.",
    flavorText: "The prime refuses to be spread thin.",
    rarity: "uncommon",
  }),
  card({
    deck: "Number Theory",
    type: "Lemma",
    name: "Bezout Lemma",
    difficulty: 2,
    requirements: ["Coprime"],
    produces: ["Bezout Lemma", "Bezout Identity"],
    description: "Turns coprimality into an integer linear combination.",
    flavorText: "Two numbers negotiate a one.",
    rarity: "uncommon",
  }),
  card({
    deck: "Number Theory",
    type: "Lemma",
    name: "Euler Phi Lemma",
    difficulty: 2,
    requirements: ["Multiplicative Group", "Coprime"],
    produces: ["Euler Phi Lemma", "Totient Control"],
    description: "Counts invertible residue classes and prepares Euler-style exponents.",
    flavorText: "The units count the legal moves.",
    rarity: "uncommon",
  }),
  card({
    deck: "Number Theory",
    type: "Lemma",
    name: "Gauss Lemma",
    difficulty: 2,
    requirements: ["Quadratic Residue", "Prime"],
    produces: ["Gauss Lemma", "Residue Reciprocity"],
    description: "Converts quadratic residue behavior into a counting sign.",
    flavorText: "Half the residues carry the secret.",
    rarity: "rare",
  }),
  card({
    deck: "Number Theory",
    type: "Proposition",
    name: "Infinitely Many Primes",
    difficulty: 2,
    requirements: ["Prime", "Divisibility"],
    produces: ["Infinitely Many Primes", "Prime Supply"],
    description: "Guarantees that arithmetic never runs out of prime atoms.",
    flavorText: "Any finite list leaves a door open.",
    rarity: "rare",
  }),
  card({
    deck: "Number Theory",
    type: "Proposition",
    name: "Euler's Theorem",
    difficulty: 2,
    requirements: ["Euler Phi Lemma", "Modular Arithmetic"],
    produces: ["Euler's Theorem", "Modular Exponent Control"],
    description: "Controls powers of coprime residues modulo n.",
    flavorText: "After enough multiplication, the unit returns.",
    rarity: "rare",
  }),
  card({
    deck: "Number Theory",
    type: "Proposition",
    name: "Fermat's Little Theorem",
    difficulty: 2,
    requirements: ["Prime Field", "Multiplicative Group"],
    produces: ["Fermat's Little Theorem", "Prime Exponent Control"],
    description: "Shows prime fields force predictable modular powers.",
    flavorText: "The prime modulus makes every nonzero residue dance in a cycle.",
    rarity: "rare",
  }),
  ...techniques("Number Theory", ["Modular Reduction", "Infinite Descent", "p-adic Valuation", "Sieve Argument"]),
  ...meta("Number Theory", ["Dirichlet Character", "Analytic Continuation", "Local-Global Principle", "Choice of Modulus"]),
  card({
    deck: "Number Theory",
    type: "Theorem",
    name: "Quadratic Reciprocity",
    difficulty: 5,
    requirements: ["Quadratic Residue", "Gauss Lemma", "Modular Reduction"],
    produces: ["Quadratic Reciprocity", "Residue Reciprocity"],
    description: "Relates whether p is a square mod q to whether q is a square mod p.",
    flavorText: "Two primes exchange a signed secret.",
    rarity: "legendary",
  }),
  card({
    deck: "Number Theory",
    type: "Theorem",
    name: "Number-Theoretic CRT",
    difficulty: 3,
    requirements: ["Bezout Lemma", "Residue Class"],
    produces: ["Chinese Remainder Engine", "Simultaneous Congruences"],
    description: "Solves compatible congruences by combining independent moduli.",
    flavorText: "Many clocks agree on one hour.",
    rarity: "rare",
  }),
  card({
    deck: "Number Theory",
    type: "Theorem",
    name: "Prime Number Theorem",
    difficulty: 5,
    requirements: ["Prime", "Sieve Argument", "Analytic Continuation"],
    produces: ["Prime Number Theorem", "Prime Density"],
    description: "Describes the asymptotic density of the primes.",
    flavorText: "Chaos thins with a logarithmic rhythm.",
    rarity: "legendary",
  }),
  card({
    deck: "Number Theory",
    type: "Theorem",
    name: "Dirichlet Arithmetic Progression Theorem",
    difficulty: 5,
    requirements: ["Dirichlet Character", "Coprime", "Analytic Continuation"],
    produces: ["Dirichlet Theorem", "Prime Progressions"],
    description: "Shows coprime arithmetic progressions contain infinitely many primes.",
    flavorText: "Every valid residue class receives infinitely many stars.",
    rarity: "legendary",
  }),
  card({
    deck: "Number Theory",
    type: "Theorem",
    name: "Hensel Lifting",
    difficulty: 4,
    requirements: ["p-adic Valuation", "Local-Global Principle"],
    produces: ["Hensel Lifting", "p-adic Root Control"],
    description: "Lifts modular roots through higher powers of a prime.",
    flavorText: "A small congruence climbs the tower.",
    rarity: "rare",
  }),
  ...definitions("Probability", [
    "Sample Space",
    "Event",
    "Random Variable",
    "Expectation",
    "Variance",
    "Independence",
    "Distribution",
    "Filtration",
    "Martingale",
  ]),
  ...examples("Probability", [
    { name: "Coin Flip Space", produces: ["Coin Flip Space", "Sample Space", "Independence"] },
    { name: "Normal Distribution", produces: ["Normal Distribution", "Distribution", "Variance"] },
    { name: "Bernoulli Trial", produces: ["Bernoulli Trial", "Random Variable"] },
    { name: "Random Walk", produces: ["Random Walk", "Martingale", "Filtration"] },
    { name: "Poisson Process", produces: ["Poisson Process", "Independent Increments"] },
    { name: "Brownian Motion", produces: ["Brownian Motion", "Martingale", "Continuity"] },
  ]),
  card({
    deck: "Probability",
    type: "Counterexample",
    name: "Heavy-Tailed Distribution",
    difficulty: 2,
    produces: ["Heavy Tail"],
    counters: ["finite variance intuition", "Dominated Estimate"],
    targetDeckStrength: strength("Probability", "Real Analysis", "hard"),
    description: "Punishes analytic estimates that assume tails decay politely.",
    flavorText: "Rare events carry impossible weight.",
    rarity: "rare",
  }),
  card({
    deck: "Probability",
    type: "Pathology",
    name: "Nonmeasurable Event",
    difficulty: 3,
    produces: ["Measurability Failure"],
    counters: ["measurability assumptions", "Integrability"],
    targetDeckStrength: strength("Probability", "Real Analysis", "hard"),
    description: "Forces analytic proofs to defend the measurable universe.",
    flavorText: "The event exists outside the ledger.",
    rarity: "rare",
  }),
  card({
    deck: "Probability",
    type: "Generalization",
    name: "Dependent Noise",
    difficulty: 2,
    produces: ["Dependence Context"],
    counters: ["independent coordinate arguments", "Basis"],
    targetDeckStrength: strength("Probability", "Linear Algebra", "soft"),
    description: "Adds dependence to strategies that rely on clean independent axes.",
    flavorText: "The dice remember each other.",
    rarity: "uncommon",
  }),
  card({
    deck: "Probability",
    type: "Pathology",
    name: "Null Set Trap",
    difficulty: 2,
    produces: ["Almost Sure Caveat"],
    counters: ["pointwise guarantees", "Path Connected"],
    targetDeckStrength: strength("Probability", "Topology", "soft"),
    description: "Turns everywhere claims into almost-sure claims with hidden exceptions.",
    flavorText: "Probability zero is not impossibility.",
    rarity: "uncommon",
  }),
  card({
    deck: "Probability",
    type: "Lemma",
    name: "Markov Inequality",
    difficulty: 1,
    requirements: ["Expectation"],
    produces: ["Markov Inequality", "Tail Bound"],
    description: "Controls large deviations from expectation.",
    flavorText: "A mean casts a long but bounded shadow.",
    rarity: "uncommon",
  }),
  card({
    deck: "Probability",
    type: "Lemma",
    name: "Chebyshev Inequality",
    difficulty: 2,
    requirements: ["Variance", "Expectation"],
    produces: ["Chebyshev Inequality", "Concentration Bound"],
    description: "Uses variance to control deviation probability.",
    flavorText: "Spread is a leash.",
    rarity: "uncommon",
  }),
  card({
    deck: "Probability",
    type: "Lemma",
    name: "Conditional Expectation Lemma",
    difficulty: 2,
    requirements: ["Expectation", "Filtration"],
    produces: ["Conditional Expectation", "Adapted Control"],
    description: "Projects uncertainty onto known information.",
    flavorText: "Tomorrow is filtered through today.",
    rarity: "uncommon",
  }),
  card({
    deck: "Probability",
    type: "Lemma",
    name: "Stopping Time Lemma",
    difficulty: 2,
    requirements: ["Martingale", "Filtration"],
    produces: ["Stopping Time Lemma", "Optional Stopping Setup"],
    description: "Prepares martingales to be stopped without losing control.",
    flavorText: "The clock is random, but it is honest.",
    rarity: "rare",
  }),
  card({
    deck: "Probability",
    type: "Proposition",
    name: "Borel-Cantelli Lemma",
    difficulty: 2,
    requirements: ["Event", "Independence"],
    produces: ["Borel-Cantelli Lemma", "Almost Sure Finiteness"],
    description: "Determines when infinitely many events occur almost surely.",
    flavorText: "Enough small chances eventually stop mattering.",
    rarity: "rare",
  }),
  card({
    deck: "Probability",
    type: "Proposition",
    name: "Linearity of Expectation",
    difficulty: 1,
    requirements: ["Random Variable", "Expectation"],
    produces: ["Linearity of Expectation", "Expectation Control"],
    description: "Adds expectations even when variables are dependent.",
    flavorText: "The mean is cooperative.",
    rarity: "uncommon",
  }),
  card({
    deck: "Probability",
    type: "Proposition",
    name: "Variance Additivity",
    difficulty: 2,
    requirements: ["Variance", "Independence"],
    produces: ["Variance Additivity", "Independent Variance Control"],
    description: "Combines variance cleanly under independence.",
    flavorText: "Independent noise stacks predictably.",
    rarity: "uncommon",
  }),
  ...techniques("Probability", ["Coupling Argument", "Moment Method", "Conditioning", "Concentration Estimate"]),
  ...meta("Probability", ["Almost Sure Framework", "Large Deviation Regime", "Stochastic Process Context", "Infinite Product Measure"]),
  card({
    deck: "Probability",
    type: "Theorem",
    name: "Law of Large Numbers",
    difficulty: 4,
    requirements: ["Chebyshev Inequality", "Independence", "Expectation Control"],
    produces: ["Law of Large Numbers", "Sample Average Control"],
    description: "Shows averages stabilize around expected value.",
    flavorText: "Randomness becomes regular in the aggregate.",
    rarity: "legendary",
  }),
  card({
    deck: "Probability",
    type: "Theorem",
    name: "Central Limit Theorem",
    difficulty: 5,
    requirements: ["Variance Additivity", "Moment Method", "Normal Distribution"],
    produces: ["Central Limit Theorem", "Gaussian Limit"],
    description: "Explains why normalized sums tend toward Gaussian shape.",
    flavorText: "Many small accidents become one bell.",
    rarity: "legendary",
  }),
  card({
    deck: "Probability",
    type: "Theorem",
    name: "Martingale Convergence Theorem",
    difficulty: 5,
    requirements: ["Martingale", "Conditional Expectation", "Stopping Time Lemma"],
    produces: ["Martingale Convergence Theorem", "Almost Sure Limit"],
    description: "Controls adapted fair processes under boundedness conditions.",
    flavorText: "A fair game eventually shows its limit.",
    rarity: "legendary",
  }),
  card({
    deck: "Probability",
    type: "Theorem",
    name: "Kolmogorov Zero-One Law",
    difficulty: 4,
    requirements: ["Independence", "Infinite Product Measure", "Event"],
    produces: ["Kolmogorov Zero-One Law", "Tail Event Certainty"],
    description: "Tail events in independent sequences have probability zero or one.",
    flavorText: "The far future leaves no middle ground.",
    rarity: "rare",
  }),
  card({
    deck: "Probability",
    type: "Theorem",
    name: "Optional Stopping Theorem",
    difficulty: 4,
    requirements: ["Stopping Time Lemma", "Martingale", "Adapted Control"],
    produces: ["Optional Stopping Theorem", "Stopped Martingale Control"],
    description: "States when stopping a martingale preserves expected value.",
    flavorText: "Stopping the game does not change fairness for free.",
    rarity: "rare",
  }),
  ...definitions("Logic & Foundations", [
    "Formal Language",
    "Axiom System",
    "Model",
    "Proof System",
    "Consistency",
    "Completeness",
    "Compactness",
    "Cardinality",
    "Recursion",
  ]),
  ...examples("Logic & Foundations", [
    { name: "Peano Arithmetic", produces: ["Peano Arithmetic", "Axiom System", "Recursion"] },
    { name: "ZFC Set Theory", produces: ["ZFC Set Theory", "Axiom System", "Cardinality"] },
    { name: "Finite Model", produces: ["Finite Model", "Model"] },
    { name: "Nonstandard Model", produces: ["Nonstandard Model", "Model", "Compactness"] },
    { name: "Truth Table", produces: ["Truth Table", "Formal Language"] },
    { name: "Countable Structure", produces: ["Countable Structure", "Cardinality"] },
  ]),
  card({
    deck: "Logic & Foundations",
    type: "Counterexample",
    name: "Skolem Paradox",
    difficulty: 2,
    produces: ["Skolem Tension"],
    counters: ["cardinality intuition", "Prime Supply"],
    targetDeckStrength: strength("Logic & Foundations", "Number Theory", "hard"),
    description: "Disrupts arguments that treat size intuition as absolute.",
    flavorText: "Countable from outside, vast from within.",
    rarity: "rare",
  }),
  card({
    deck: "Logic & Foundations",
    type: "Pathology",
    name: "Undecidable Sentence",
    difficulty: 3,
    produces: ["Undecidable Sentence"],
    counters: ["complete axiomatization", "Choice-Dependent Construction"],
    targetDeckStrength: strength("Logic & Foundations", "Number Theory", "hard"),
    description: "Adds a meta-proof requirement to arithmetic theorem chains.",
    flavorText: "The sentence waits outside the proof system.",
    rarity: "rare",
  }),
  card({
    deck: "Logic & Foundations",
    type: "Generalization",
    name: "Large Cardinal Assumption",
    difficulty: 3,
    produces: ["Large Cardinal Assumption"],
    counters: ["set-theoretic minimalism", "Cardinal Explosion"],
    targetDeckStrength: strength("Logic & Foundations", "Topology", "soft"),
    description: "Escalates the foundation under theorem attempts.",
    flavorText: "The universe grows another inaccessible height.",
    rarity: "rare",
  }),
  card({
    deck: "Logic & Foundations",
    type: "Counterexample",
    name: "Independence Result",
    difficulty: 3,
    produces: ["Independence Result"],
    counters: ["absolute theorem claims", "Completeness"],
    targetDeckStrength: strength("Logic & Foundations", "Abstract Algebra", "soft"),
    description: "Forces a proof to name its axioms before it can proceed.",
    flavorText: "Some doors open only in selected universes.",
    rarity: "rare",
  }),
  card({
    deck: "Logic & Foundations",
    type: "Lemma",
    name: "Soundness Lemma",
    difficulty: 2,
    requirements: ["Proof System", "Model"],
    produces: ["Soundness Lemma", "Semantic Validity"],
    description: "Connects formal proofs to truth in all models.",
    flavorText: "A derivation cannot lie in any model.",
    rarity: "uncommon",
  }),
  card({
    deck: "Logic & Foundations",
    type: "Lemma",
    name: "Henkin Construction",
    difficulty: 2,
    requirements: ["Formal Language", "Consistency"],
    produces: ["Henkin Construction", "Witness Constants"],
    description: "Adds witnesses to build models from consistent theories.",
    flavorText: "Every existential demand receives a name.",
    rarity: "uncommon",
  }),
  card({
    deck: "Logic & Foundations",
    type: "Lemma",
    name: "Diagonal Lemma",
    difficulty: 3,
    requirements: ["Recursion", "Formal Language"],
    produces: ["Diagonal Lemma", "Self Reference"],
    description: "Builds sentences that can speak about their own provability.",
    flavorText: "The formula turns and sees itself.",
    rarity: "rare",
  }),
  card({
    deck: "Logic & Foundations",
    type: "Lemma",
    name: "Ultraproduct Lemma",
    difficulty: 3,
    requirements: ["Model", "Compactness"],
    produces: ["Ultraproduct Lemma", "Model Transfer"],
    description: "Transfers first-order truths through filtered products.",
    flavorText: "Many structures vote through an ultrafilter.",
    rarity: "rare",
  }),
  card({
    deck: "Logic & Foundations",
    type: "Proposition",
    name: "Every Proof Is Finite",
    difficulty: 1,
    requirements: ["Proof System"],
    produces: ["Finite Proof", "Syntactic Control"],
    description: "Turns proof objects into finite combinatorial data.",
    flavorText: "Infinity may be discussed, but proofs arrive line by line.",
    rarity: "uncommon",
  }),
  card({
    deck: "Logic & Foundations",
    type: "Proposition",
    name: "Models Satisfy Theories",
    difficulty: 1,
    requirements: ["Model", "Axiom System"],
    produces: ["Satisfaction Relation", "Semantic Control"],
    description: "Makes model checking available as a proof-state fact.",
    flavorText: "A model is where axioms become weather.",
    rarity: "uncommon",
  }),
  card({
    deck: "Logic & Foundations",
    type: "Proposition",
    name: "Countable Language Bound",
    difficulty: 2,
    requirements: ["Formal Language", "Cardinality"],
    produces: ["Countable Language Bound", "Cardinality Control"],
    description: "Controls the size of syntactic objects in countable languages.",
    flavorText: "There are only so many finite strings.",
    rarity: "rare",
  }),
  ...techniques("Logic & Foundations", ["Model Construction", "Forcing Argument", "Diagonalization", "Compactness Argument"]),
  ...meta("Logic & Foundations", ["Choice Principle", "Metatheory Layer", "Incompleteness Context", "Reflection Principle"]),
  card({
    deck: "Logic & Foundations",
    type: "Theorem",
    name: "Compactness Theorem",
    difficulty: 4,
    requirements: ["Henkin Construction", "Finite Proof", "Compactness Argument"],
    produces: ["Compactness Theorem", "Finite Satisfiability"],
    description: "If every finite part of a theory has a model, the whole theory has a model.",
    flavorText: "Finite consistency echoes into the infinite.",
    rarity: "legendary",
  }),
  card({
    deck: "Logic & Foundations",
    type: "Theorem",
    name: "Completeness Theorem",
    difficulty: 5,
    requirements: ["Soundness Lemma", "Henkin Construction", "Consistency"],
    produces: ["Completeness Theorem", "Proof-Model Bridge"],
    description: "Connects semantic entailment and syntactic provability for first-order logic.",
    flavorText: "What holds in every model can be proven.",
    rarity: "legendary",
  }),
  card({
    deck: "Logic & Foundations",
    type: "Theorem",
    name: "Incompleteness Theorem",
    difficulty: 5,
    requirements: ["Diagonal Lemma", "Peano Arithmetic", "Consistency"],
    produces: ["Incompleteness Theorem", "Undecidability Engine"],
    description: "Shows sufficiently strong consistent arithmetic cannot prove every truth.",
    flavorText: "Arithmetic writes the sentence it cannot settle.",
    rarity: "legendary",
  }),
  card({
    deck: "Logic & Foundations",
    type: "Theorem",
    name: "Lowenheim-Skolem Theorem",
    difficulty: 4,
    requirements: ["Countable Language Bound", "Model Construction", "Cardinality"],
    produces: ["Lowenheim-Skolem Theorem", "Elementary Submodel Control"],
    description: "Controls model sizes while preserving first-order truth.",
    flavorText: "Truth survives the change of scale.",
    rarity: "rare",
  }),
  card({
    deck: "Logic & Foundations",
    type: "Theorem",
    name: "Tarski Undefinability",
    difficulty: 4,
    requirements: ["Diagonal Lemma", "Formal Language", "Truth Table"],
    produces: ["Tarski Undefinability", "Truth Boundary"],
    description: "Shows truth for arithmetic cannot be defined inside arithmetic itself.",
    flavorText: "Truth refuses to fit in its own mirror.",
    rarity: "rare",
  }),
];

export const CARDS_BY_DECK = Object.fromEntries(
  DECKS.map((deck) => [deck, ALL_CARDS.filter((cardItem) => cardItem.deck === deck)])
);

export const getTheoremDeck = (deck) =>
  CARDS_BY_DECK[deck].filter((cardItem) => cardItem.type === "Theorem");

export const getMainDeck = (deck) =>
  CARDS_BY_DECK[deck].filter((cardItem) => cardItem.type !== "Theorem");
